- name: Deploy to EC2 to pass this subject
  hosts: localhost
  connection: local
  tasks:
    - name: Identify running instances
      ec2_instance_info:
        region: us-east-1
        aws_access_key: "ASIAWLMA2LRWQWHGWA7Y"
        aws_secret_key: "qfX2jouAyRKnBP/lpj4gWxHaBi6ZqbASjYz7RL4D"
        security_token: "FwoGZXIvYXdzEN3//////////wEaDC4SyrTjzBua84akeiLEAcdyTOJ+HdC2J5YihEvLvCKarUgAsZGz0V2LKyZ2hgQIG+Y3PSeIDmM25AwZXj55M8kMDJrK4iZnM8hJNQy+ex4JUR4zWYlgoiDXfDBVAkZSnMx3M+dop+zi78jvqA/u5jheU45aGgqgWMengGxcyxQe0Ucx6AnnNSXL3elY7vD+w9lzBdd4rhGAcvekGpfjPykVWBbYBtb+URO7SsJKPN5+rs4TOXtxYxtn+RANkYEfRTtsUreybHAcrYdg8OMz0omkzpQo6/f8/gUyLb0IVeM0Tc0Ve5gmwC9mRtoWuePMfA1ZYQq8gnxxM/gkW5frPx/3llAeVtCV1g=="
      register: ec2_stat
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-00ddb0e5626798373
        region: us-east-1
        key_name: accessKey
        vpc_subnet_id: subnet-d3448fe2
        assign_public_ip: yes
        wait: yes
        count: 1
        group: semestralka
        aws_access_key: "ASIAWLMA2LRWQWHGWA7Y"
        aws_secret_key: "qfX2jouAyRKnBP/lpj4gWxHaBi6ZqbASjYz7RL4D"
        security_token: "FwoGZXIvYXdzEN3//////////wEaDC4SyrTjzBua84akeiLEAcdyTOJ+HdC2J5YihEvLvCKarUgAsZGz0V2LKyZ2hgQIG+Y3PSeIDmM25AwZXj55M8kMDJrK4iZnM8hJNQy+ex4JUR4zWYlgoiDXfDBVAkZSnMx3M+dop+zi78jvqA/u5jheU45aGgqgWMengGxcyxQe0Ucx6AnnNSXL3elY7vD+w9lzBdd4rhGAcvekGpfjPykVWBbYBtb+URO7SsJKPN5+rs4TOXtxYxtn+RANkYEfRTtsUreybHAcrYdg8OMz0omkzpQo6/f8/gUyLb0IVeM0Tc0Ve5gmwC9mRtoWuePMfA1ZYQq8gnxxM/gkW5frPx/3llAeVtCV1g=="
      register: ec2

    - name: Add instance to host
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=900 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get files from GIT repository
      git:
        repo: 'https://github.com/janpapez123/trying.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 70
      poll: 0
      become: yes
    - wait_for:
        port: 80

- name: Terminate instances
  hosts: localhost
  connection: local

  tasks:
   - name: Terminate running instances
     ec2:
       region: us-east-1
       state: absent
       aws_access_key: "ASIAWLMA2LRW54SRFIJV"
       aws_secret_key: "4KN9sab6hS7AEmAtkYM5el1uN+Pa+zgL7fKb3DCx"
       security_token: "FwoGZXIvYXdzENr//////////wEaDF6ZdmOlJtkAQenOUSLEAVbrE51ZEZqX1Ld59dJS5FlZqi/7M1RIGhKExsmCK6AKsq60BVnuKwgt7bfvPgL2q++MPd4eP/a1mPt3FkNHIB2M5UIxOQJi2VxF6+eTRuEp+y/qV3S/bmjcJ9FgKCyAUfutXRdcj4sMGMHISMw7T/4Ue27DQBafIDAA5H8TQ4H+XYMYVXoxTk4/bqLT2HYnVVJqPL84qnVFZvz2j1veA/aLLond457pcWNxqqD8jS7zHx3K0pr29TJd81uRJSxSIERCW0Yozpb8/gUyLVEKYdxEV40OdgTAkDJ65/L1HU99X7zM2tOJs4e33hA1OaBZ9S7P1Edgd5tiXA=="
       instance_ids: '{{ item.instance_id }}'
     loop: "{{ ec2_stat.instances }}"
     loop_control:
       label: "{{ item.instance_id }}"
